### ISSUE TITLE
关于数据集KittiDatasetSFD报错的问题

### ISSUE THREAD

**Issue by xinpuliu** [LittlePey/SFD#22]
你好，我复现代码的时候，按照您给的数据集结构组织了文件夹，在运行如下代码时，报错了，请问你知道这是什么问题嘛？
scripts/dist_train.sh 4 --cfg_file cfgs/kitti_models/sfd.yaml --gpu_id 0,1,2,3
![微信截图_20220828104526](https://user-images.githubusercontent.com/61619158/187055227-fc3e10ba-9278-4344-90b4-9f44f1a41200.png)

报错：
Traceback (most recent call last):
  File "train.py", line 200, in <module>
    main()
  File "train.py", line 114, in main
    total_epochs=args.epochs
  File "/home/fuwuqianyan/LXP/OpenPCDet/pcdet/datasets/__init__.py", line 53, in build_dataloader
    dataset = __all__[dataset_cfg.DATASET](
**KeyError: 'KittiDatasetSFD'**
Killing subprocess 3833
Killing subprocess 3834
Killing subprocess 3835
Killing subprocess 3836
Traceback (most recent call last):
  File "/home/fuwuqianyan/anaconda3/envs/wunai3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/fuwuqianyan/anaconda3/envs/wunai3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/fuwuqianyan/anaconda3/envs/wunai3/lib/python3.7/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/fuwuqianyan/anaconda3/envs/wunai3/lib/python3.7/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/fuwuqianyan/anaconda3/envs/wunai3/lib/python3.7/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/fuwuqianyan/anaconda3/envs/wunai3/bin/python', '-u', 'train.py', '--local_rank=3', '--launcher', 'pytorch', '--cfg_file', 'cfgs/kitti_models/sfd.yaml', '--gpu_id', '0,1,2,3']' returned non-zero exit status 1.

**Comment by Raiden-cn** [comment]
You may need to reinstall the OpenPCDet.
Cuz OpenPCDet is use the way of  develop to insatll.
It should be `'SFD2/pcdet/datasets/init.py'`, instead of `File "/home/fuwuqianyan/LXP/OpenPCDet/pcdet/datasets/init.py", line 53, in build_dataloader`.

**Comment by liuyangme** [comment]
请问解决了吗？我也一直卡在这里，没有找到解决办法，求助！

**Comment by hailanyi** [comment]
@liuyang9609 你之前估计是安装过OpenPCDet. 所以运行SFD的时候直接从OpenPCDet读文件了。有两个方法解决：（1）重新安装SFD，如果还不行就卸载掉之前的OpenPCDet再安装SFD。（2）把SFD的路径加到PYTHONPATH中， 比如在.bashrc中加入
```
export PYTHONPATH=/home/SFD:$PYTHONPATH
```
注释掉这个路径，还可以运行之前安装的OpenPCDet。

**Comment by liuyangme** [comment]
> @liuyang9609 你之前估计是安装过OpenPCDet. 所以运行SFD的时候直接从OpenPCDet读文件了。有两个方法解决：（1）重新安装SFD，如果还不行就卸载掉之前的OpenPCDet再安装SFD。（2）把SFD的路径加到PYTHONPATH中， 比如在.bashrc中加入
> 
> ```
> export PYTHONPATH=/home/SFD:$PYTHONPATH
> ```
> 
> 注释掉这个路径，还可以运行之前安装的OpenPCDet。

好的，我试试看，谢谢您！

**Comment by Karkers** [comment]
> @liuyang9609 你之前估计是安装过OpenPCDet. 所以运行SFD的时候直接从OpenPCDet读文件了。有两个方法解决：（1）重新安装SFD，如果还不行就卸载掉之前的OpenPCDet再安装SFD。（2）把SFD的路径加到PYTHONPATH中， 比如在.bashrc中加入
> 
> ```
> export PYTHONPATH=/home/SFD:$PYTHONPATH
> ```
> 
> 注释掉这个路径，还可以运行之前安装的OpenPCDet。

Doesn't SFD depend on Openpcdet, how can I reinstall PCDET in SFD?

**Comment by Karkers** [comment]
> > @liuyang9609 你之前估计是安装过OpenPCDet. 所以运行SFD的时候直接从OpenPCDet读文件了。有两个方法解决：（1）重新安装SFD，如果还不行就卸载掉之前的OpenPCDet再安装SFD。（2）把SFD的路径加到PYTHONPATH中， 比如在.bashrc中加入
> > ```
> > export PYTHONPATH=/home/SFD:$PYTHONPATH
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 注释掉这个路径，还可以运行之前安装的OpenPCDet。
> 
> 好的，我试试看，谢谢您！

您好，我想问一下这个重装SFD，sfd不是得安装openpcdet么，源码里有pcdet文件，我应该怎么编译去安装。
