### ISSUE TITLE
KittiDataset

### ISSUE THREAD

**Issue by Karkers** [LittlePey/SFD#52]
ImportError: cannot import name 'KittiDataset' from 'pcdet.datasets.kitti.kitti_dataset' (/home/karker/PROJ/SFD/pcdet/datasets/kitti/kitti_dataset.py)
What can in do for this question?Help

**Comment by Karkers** [comment]
ImportError: cannot import name 'VoxelBackBone4x' from 'pcdet.models.backbones_3d.spconv_backbone'I have another question！！！

**Comment by Michal12Zurawka** [comment]
hello, how you defeat problem with kitti dataset?
Traceback (most recent call last):
  File "train.py", line 200, in <module>
    main()
  File "train.py", line 106, in main
    train_set, train_loader, train_sampler = build_dataloader(
  File "/home/m/Desktop/TED/pcdet/datasets/__init__.py", line 52, in build_dataloader
    dataset = __all__[dataset_cfg.DATASET](
KeyError: 'KittiDatasetSFD
